wandb_version: 1

name:
  desc: null
  value: WandB Test Run
lr:
  desc: null
  value: 0.0001
lr_decay:
  desc: null
  value: 0.999
exploration_decay:
  desc: null
  value: 0.995
n_actions:
  desc: null
  value: 7
gamma:
  desc: null
  value: 0.9
episodes:
  desc: null
  value: 1000
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682135692.653287
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 16
      - 23
      4: 3.10.11
      5: 0.15.0
      8:
      - 1
      - 4
      - 5
